(rule
 (deps Basic.fl)
 (action
  (with-stdout-to
   Basic_fl_actual.sexp
   (run %{bin:fl} -i fl -o sexp %{deps}))))

(rule
 (deps Basic.fl)
 (action
  (with-stdout-to
   Basic_actual.ml
   (pipe-stdout
     (run %{bin:fl} -i fl -o ml %{deps})
     (run %{bin:ocamlformat} --impl -)))))

(rule
 (alias runtest)
 (action
  (diff Basic_expected.ml Basic_actual.ml)))

(rule
 (alias runtest)
 (action
  (diff Basic_expected.sexp Basic_fl_actual.sexp)))

; (rule
;  (deps Either.fl)
;  (action
;   (with-stdout-to
;    Either_actual.ml
;    (pipe-stdout
;     (run %{bin:fl} %{deps})
;     (run %{bin:ocamlformat} --impl -)))))
;
; (rule
;  (alias runtest)
;  (action
;   (diff Either_expected.ml Either_actual.ml)))
